config/routes.rb
Rails.application.routes.draw do


  devise_for :employees
  devise_for :users
  
  #get "users/sign_out" => 'pages#index'
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  root 'pages#index'

  resources :leads

  # get 'userinfo' => 'pages#userinfo'

  delete 'userinfo' => 'pages#destroy'

  delete 'index' => 'pages#destroy'

  post 'root' => 'root#sendInformation'

  post 'index' => 'pages#create'
  
  post 'index' => 'pages#create'
  mount Blazer::Engine, at: "blazer"

  get 'home' => 'pages#home'
 
  #get 'newintervention' => 'interventions#newintervention'

  get 'corporate'  => 'pages#corporate'
  get 'test'  => 'pages#test'

  get 'residential'  => 'pages#residential'

  get 'submission' => 'quotes#submission'

  post 'submission' => 'quotes#create'

  get 'employee' => 'pages#employee'

  get 'submission' => 'pages#submission'
  
  get 'index' => 'pages#index'

  get 'users/index' => 'pages#index'
  
  get 'users/index' => 'pages#index'
  
  get 'employee' => 'pages#employee'
  
  get 'dashboard' => 'pages#dashboard'



  get 'dashboard/building' => 'dashboard#building'

  #post '/interventions' => 'interventions#create_intervention'

  post 'interventions' => 'interventions#create'
  get 'interventions' => 'interventions#interventions'

  get 'interventions/building' => 'interventions#building'
  get 'interventions/battery' => 'interventions#battery'
  get 'interventions/column' => 'interventions#column'
  get 'interventions/elevator' => 'interventions#elevator'
  gem 'newrelic_rpm'
  resources :geolocations

  
end

app/models/geolocation.rb
class Geolocation < ApplicationRecord
    
end

app/controllers/geolocations_controller.rb
class GeolocationsController < ApplicationController
  before_action :set_geolocation, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :exception

  # GET /geolocations
  # GET /geolocations.json
  def index
    @geolocations = Geolocation.all
    @address = Address.all
    @elevator = Elevator.all
 
  end

  # GET /geolocations/1
  # GET /geolocations/1.json
  def show
    @elevator = Elevator.all
    @building = Building.all

    Building.find_each do |building|

      address = building.address
      b = building.batteries.count
      b_ids = building.battery_ids
      @c = Column.where(battery_id: b_ids).count
      c_ids = Column.where(battery_id: building.battery_ids).ids
      @e = Elevator.where(column_id: c_ids).count

    end

  end

  # GET /geolocations/new
  def new
    @geolocation = Geolocation.new
    @address = Address.new
  end

  # GET /geolocations/1/edit
  def edit
  end

  # POST /geolocations
  # POST /geolocations.json
  def create
    @geolocation = Geolocation.new(geolocation_params)

    respond_to do |format|
      if @geolocation.save
        format.html { redirect_to @geolocation, notice: 'Geolocation was successfully created.' }
        format.json { render :show, status: :created, location: @geolocation }
      else
        format.html { render :new }
        format.json { render json: @geolocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geolocations/1
  # PATCH/PUT /geolocations/1.json
  def update
    respond_to do |format|
      if @geolocation.update(geolocation_params)
        format.html { redirect_to @geolocation, notice: 'Geolocation was successfully updated.' }
        format.json { render :show, status: :ok, location: @geolocation }
      else
        format.html { render :edit }
        format.json { render json: @geolocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geolocations/1
  # DELETE /geolocations/1.json
  def destroy
    @geolocation.destroy
    respond_to do |format|
      format.html { redirect_to geolocations_url, notice: 'Geolocation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geolocation
      @geolocation = Geolocation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def geolocation_params
      params.require(:geolocation).permit(:name, :latitude, :longitude)
    end
end

app/helpers/geolocations_helper.rb
module GeolocationsHelper
end

app/views/geolocations/_form.html.erb
<%= form_with(model: geolocation, local: true) do |form| %>
  <% if geolocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(geolocation.errors.count, "error") %> prohibited this geolocation from being saved:</h2>

      <ul>
      <% geolocation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/geolocations/edit.html.erb
<h1>Editing Geolocation</h1>

<%= render 'form', geolocation: @geolocation %>

<%= link_to 'Show', @geolocation %> |
<%= link_to 'Back', geolocations_path %>

app/views/geolocations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Geolocations</h1>

<table>
  <thead>
    <tr>
      <th>Click below to access Locations</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geolocations.each do |geolocation| %>
      <tr>

        <td><%= link_to 'Show Locations', geolocation %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/geolocations/new.html.erb
<h1>New Geolocation</h1>

<%= render 'form', geolocation: @geolocation %>

<%= link_to 'Back', geolocations_path %>

app/views/geolocations/show.html.erb
<html>
<head>
 <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">

<style>
#map {
    height: 100%;
  }
  /* Optional: Makes the sample page fill the window. */
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
</style>
 </head>
  <body>
 <div id="map"></div>
    <script>
    
      function initMap() {

          var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 49.516667 , lng: -115.766667},
          zoom: 8
        });

    <% @building.each do |b| %>

       var myLatLng = {lat: <%= b.address.latitude %>, lng: <%= b.address.longitude %>};
       
        var marker = new google.maps.Marker({
           position: myLatLng,
           map: map,
  });


  var contentString = '<div id="content">'+
      '<div id="siteNotice">'+
      '</div>'+
      '<h1 id="firstHeading" class="firstHeading"><%= b.id %></h1>'+
      '<div id="bodyContent">'+
      '<p><b>Building</b> is located at <b><%= b.address.city + ", " + b.address.state_province %></b>' +
      ' number of floors is:  '+
      '<%=  @e %> '+
      'client name is '+
      '<%= b.customer.contact_full_name %> '+
      ' Number of Batteries: '+
      '<%=  b.batteries.count %>  '+
      ' Number of Columns: '+
      '<%=  @c %> '+
      ' Number of Elevators: '+
      '<%=  @e %>'+
      ' Full name of technical contact: '+
      '<%=  b.building_technical_contact_name %></p>';

      marker.infowindow = new google.maps.InfoWindow({
            content: contentString
            });


      marker.addListener('click', function() {

          this.infowindow.open(map, this);
      });
      


    <% end %>


      }
      
    </script>


    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_api_key'] %>&callback=initMap"
    async defer>
    </script>



<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_geolocation_path(@geolocation) %> |
<%= link_to 'Back', geolocations_path %>

</body>
</html>